#!/bin/bash

# revdescr
rdescr="$*";
[ -z "$rdescr" ] && rdescr="$(date)"

comma=" "
cmdh=include/30-rpc-cmd.h
idsh=include/30-rpc-ids.h
cat > $idsh << EOT
#ifndef __RPC_IDS__
#define __RPC_IDS__
enum RPC_ids { 
EOT
cat > $cmdh << EOT
#ifndef __RPC_CMD__
#define __RPC_CMD__
static const char *RPC_cmd[] = {
EOT
sort ZZZ_RPC_List.txt | while read rpc_cmd; do
	rpc_cmd=$(sed 's/ //g' <<< $rpc_cmd)
	[ -z "$rpc_cmd" ] && continue;
	echo $rpc_cmd 1>&2
	rpc_id=$(sed -e 's/[.]/_/g' -e 's/[|]//g' <<< $rpc_cmd)
	echo -e "${comma}$rpc_id" >> $idsh
	echo -e "${comma}\"$rpc_cmd\"" >> $cmdh
	comma=","
done 
tee -a $cmdh >> $idsh << EOT
};
#endif
EOT

# Generates prototypes
for fn in src/*.c*; do
	fh=$(sed -E -e 's/[.].*/.h/g' -e 's/.*\//include\//g' <<< $fn)
	ft="__PROTO_$(sed -E -e 's/[.-]/_/g' -e 's/.*\///g' <<< $fn | tr '[:lower:]' '[:upper:]')__"
	echo "extracting prototypes from  $fn to $fh: $ft ..." 1>&2
	echo -n > $fh
	echo "#ifndef $ft" >> $fh
	echo "#define $ft" >> $fh
	echo "//Extracted Prototyes" >> $fh
	echo "// ****************************" >> $fh 
	echo "// $fn prototypes" >> $fh
	echo "// ****************************" >> $fh
	grep '[a-z0-9A-Z_]\+ [a-z0-9A-Z_*]\+ *([a-z0-9A-Z,*& _.]*) *{' "$fn" \
		| grep -v static \
		| sed  -e 's/ {.*$/;/g' \
		>> $fh
	echo "#endif" >> $fh
done 


# updates to last revision
git add . -A
git commit -m "$rdescr" -a
git push

cat > include/revision.h << EOT
#define REVISION "$(git rev-parse --short HEAD) $(git log -1 --format=%cd | tail -n 1)" 
EOT

