#ifndef __RPC_CMD__
#define __RPC_CMD__
static const char *RPC_cmd[] = {
 "CFG.Debug"
,"CFG.Leds.Disable"
,"CFG.Leds.Enable"
,"CFG.LOG.Local"
,"CFG.LOG.Mqtt"
,"CFG.LOG.None"
,"CFG.LOG.Off"
,"CFG.Modbus.AddCall"
,"CFG.Modbus.Timeout"
,"CFG.Modbus.Timestep"
,"CFG.Sys.Timestep"
,"RPC.Disable.All"
,"RPC.Disable.Modbus"
,"RPC.Disable.Sys"
,"RPC.Enable.All"
,"RPC.Enabled.All"
,"RPC.Enabled.Modbus"
,"RPC.Enabled.Sys"
,"RPC.Enable.Modbus"
,"RPC.Enable.Sys"
,"RPC.List"
,"RPC.Relay.Off"
,"RPC.Relay.On"
,"RPC.Trigger"
,"Sys.Cancel.Reboot"
,"Sys.GetInfo"
,"Sys.GetStatus"
,"Sys.Identify"
,"Sys.Reboot"
,"Sys.Update.Cancel"
,"Sys.Update.Filesystem"
,"Sys.Update.Firmware"
,"Sys.WiFi.Disconnect"
};
#endif
