#ifndef __RPC_CMD__
#define __RPC_CMD__
static const char *RPC_cmd[] = {
 "CFG.Debug"
,"CFG.Leds.Disable"
,"CFG.Leds.Enable"
,"CFG.LOG.Local"
,"CFG.LOG.Mqtt"
,"CFG.LOG.None"
,"CFG.LOG.Off"
,"CFG.Modbus.AddCall"
,"CFG.Modbus.Timeout"
,"CFG.Modbus.Timestep"
,"CFG.Sys.Timestep"
,"RPC.Disable"
,"RPC.Enable"
,"RPC.Enabled"
,"RPC.List"
,"RPC.Relay.Off"
,"RPC.Relay.On"
,"RPC.Trigger"
,"Sys.Cancel.Reboot"
,"Sys.GetInfo"
,"Sys.GetStatus"
,"Sys.Identify"
,"Sys.OTA.Cancel"
,"Sys.OTA.Update"
,"Sys.Reboot"
,"Sys.Update.Cancel"
,"Sys.Update.Filesystem"
,"Sys.Update.Firmware"
,"Sys.WiFi.Disconnect"
,"Sys.WiFi.Setup"
};
#endif
